version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
    exclude_patterns:
    - "spec/**/*"
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-49
exclude_patterns:
- "**/vendor/**/*"
